// run with
// npm run indexl10n
// or
// node scripts/translation-index.js

/**
 * @fileoverview This generates the following files:
 * src/lib/resources/localization/translation/language/language-database.js
 * src/lib/resources/localization/translation/language/language-info.js
 * src/lib/types/translation-index.d.ts
 */
import fs from "fs"
import path from "path"
const folderPath = path.join(import.meta.dirname, "../src/lib/resources/localization/translation/language/");
const outputLanguagesPath = path.join(import.meta.dirname, "../src/lib/resources/localization/translation/language/language-database.js");
const outputLanguageInfoPath = path.join(import.meta.dirname, "../src/lib/resources/localization/translation/language/language-info.js");
const outputLanguageTypesPath = path.join(import.meta.dirname, "../src/lib/types/translation-index.d.ts");

import en from '../src/lib/resources/localization/translation/language/en.json' with { type: "json" };

// NOTE: This is where manual stuff can be defined
// add languages that are RTL here
const rtlLanguages = [
    "he",                          // Hebrew
    "fa",                          // Persian
    "ar",                          // Arabic

    "en-reversed",                 // joke (programatic): English (reversed)
    "en-flipped",                  // joke (programatic): English (flipped)
];
// set pairs for language codes that should be interpreted as another language code
// NOTE: remove language codes from here if/when they get translated as a separate language (ex, portuguese is listed as pt-br because we dont have portuguese)
const autoLocale = {
    "nn": "no",
    "nb": "no",
    "es-es": "es",
    "pt": "pt-br",
    "fr-fr": "fr",
    "nl-nl": "nl",
    "ar-sa": "ar",
};

// NOTE: The joke lang list is generated by programatic-langs.js
const jokeLangsList = path.join(folderPath, "jokelangs.txt");
const jokeLangsArray = JSON.parse(fs.readFileSync(jokeLangsList, "utf8"));

// NOTE: We pre-calculate these because there are a few thousand strings in PM now
import { getLanguageFinishedPercentage } from "./finished-percentage.js";

const dirents = fs.readdirSync(folderPath, { withFileTypes: true });
const mapping = dirents
    .filter(dirent => dirent.name.endsWith(".json"))
    .map(dirent => ({
        importPath: `./${dirent.name}`,
        safeName: `_${dirent.name}_${Math.random()}`.replace(/[^a-z0-9]/gi, "_"),
        languageCode: `${dirent.name.replace(".json", "")}`,
        json: JSON.parse(fs.readFileSync(path.join(folderPath, dirent.name), "utf8"))
    }));
// language-database.js
const outputDatabaseText = `/**!
 * @fileoverview This file is automatically generated based off of PenguinMod's Translations Google Sheet.
 * Please notify a developer or make an issue if you would like to contribute to translating PenguinMod.
 * 
 * Do not edit this file manually. Pull requests and modifications to this file will not be accepted :(
 * Please notify a developer or make an issue if you would like to contribute to translating PenguinMod.
 * 
 * If you are a developer, you can re-index the translations folder with:
 * \`npm run indexl10n\`
 *
 * Please notify a developer or make an issue if you would like to contribute to translating PenguinMod.
 */
${mapping.map(lang => `import ${lang.safeName} from "${lang.importPath}";`).join("\n")}
export default {
${mapping.map(lang => `"${lang.languageCode}": ${lang.safeName},`).join("\n")}
};

/**!
 * @fileoverview This file is automatically generated based off of PenguinMod's Translations Google Sheet.
 * Please notify a developer or make an issue if you would like to contribute to translating PenguinMod.
 * 
 * Do not edit this file manually. Pull requests and modifications to this file will not be accepted :(
 * Please notify a developer or make an issue if you would like to contribute to translating PenguinMod.
 * 
 * If you are a developer, you can re-index the translations folder with:
 * \`npm run indexl10n\`
 *
 * Please notify a developer or make an issue if you would like to contribute to translating PenguinMod.
 */
`
// language-info.js
const outputInfoText = `/**!
 * @fileoverview This file is automatically generated based off of PenguinMod's Translations Google Sheet.
 * Please notify a developer or make an issue if you would like to contribute to translating PenguinMod.
 * 
 * Do not edit this file manually. Pull requests and modifications to this file will not be accepted :(
 * Please notify a developer or make an issue if you would like to contribute to translating PenguinMod.
 * 
 * If you are a developer, you can re-index the translations folder with:
 * \`npm run indexl10n\`
 *
 * Please notify a developer or make an issue if you would like to contribute to translating PenguinMod.
 */
/**
 * A large table of language info.
 */
const languageInfo = {};
/**
 * The mappings of language code to language name.
 */
languageInfo.languageName = {
${mapping.map(lang => `"${lang.languageCode}": ${JSON.stringify(lang.json["lang.name"])},`).join("\n")}
};
/**
 * The list of language codes that are marked as joke languages.
 * This is specified in \`scripts/programatic-langs.js\` even for non-automatically-generated languages.
 */
languageInfo.languageJokeList = ${JSON.stringify(jokeLangsArray)};
/**
 * The list of language codes that are marked as Right-To-Left languages.
 * This is specified in \`scripts/translation-index.js\`
 */
languageInfo.languageRtlList = ${JSON.stringify(rtlLanguages)};
/**
 * Mapping of language codes that do not have translations, but map to similar languages that are.
 * This is specified in \`scripts/translation-index.js\`
 */
languageInfo.languageAlternative = ${JSON.stringify(autoLocale)};
/**
 * Maps whether or not a language code is a joke language.
 */
languageInfo.languageJoke = {
${mapping.map(lang => `"${lang.languageCode}": ${jokeLangsArray.includes(lang.languageCode)},`).join("\n")}
};
/**
 * Maps whether or not a language code is a Right-To-Left language.
 */
languageInfo.languageRtl = {
${mapping.map(lang => `"${lang.languageCode}": ${rtlLanguages.includes(lang.languageCode)},`).join("\n")}
};
/**
 * The order that languages should be listed in alphabetically (A-Z).
 */
languageInfo.languageOrder = [
${mapping.toSorted((langA, langB) => (langA.json["lang.name"]).localeCompare(langB.json["lang.name"])).map(lang => `"${lang.languageCode}",`).join("\n")}
];
/**
 * Maps the percentage (0-1) that a language has been translated.
 */
languageInfo.finishedPercentage = {
${mapping.map(lang => `"${lang.languageCode}": ${getLanguageFinishedPercentage(lang.languageCode, lang.json)},`).join("\n")}
};
export default languageInfo;

/**!
 * @fileoverview This file is automatically generated based off of PenguinMod's Translations Google Sheet.
 * Please notify a developer or make an issue if you would like to contribute to translating PenguinMod.
 * 
 * Do not edit this file manually. Pull requests and modifications to this file will not be accepted :(
 * Please notify a developer or make an issue if you would like to contribute to translating PenguinMod.
 * 
 * If you are a developer, you can re-index the translations folder with:
 * \`npm run indexl10n\`
 *
 * Please notify a developer or make an issue if you would like to contribute to translating PenguinMod.
 */

`;

const outputTypesText = `
/**!
 * @fileoverview This file is automatically generated based off of PenguinMod's Translations Google Sheet.
 * Please notify a developer or make an issue if you would like to contribute to translating PenguinMod.
 *
 * Do not edit this file manually. Pull requests and modifications to this file will not be accepted :(
 * Please notify a developer or make an issue if you would like to contribute to translating PenguinMod.
 *
 * If you are a developer, you can re-index the translations folder with:
 * \`npm run indexl10n\`
 *
 * Please notify a developer or make an issue if you would like to contribute to translating PenguinMod.
 */

declare namespace TranslationIndex {
    /**
     * Which language codes are supported in PenguinMod-Home currently.
     * ${mapping.map(lang => `- \`"${lang.languageCode}"\` = ${lang.json["lang.name"]}`).join("\n     * ")}
     */
    type LanguageCode = ${mapping.map(lang => JSON.stringify(`${lang.languageCode}`)).join("\n\t\t| ")};
    /**
     * A listing of all valid text strings.
     */
    type Key = ${Object.keys(en).filter(key => !(key.startsWith("---") || key.startsWith("_"))).map(key => JSON.stringify(`${key}`)).join("\n\t\t| ")};
    /**
     * A listing of all existing English strings.
     */
    type Text = ${Object.values(en).map(key => JSON.stringify(`${key}`)).join("\n\t\t| ")};
}


/**!
 * @fileoverview This file is automatically generated based off of PenguinMod's Translations Google Sheet.
 * Please notify a developer or make an issue if you would like to contribute to translating PenguinMod.
 *
 * Do not edit this file manually. Pull requests and modifications to this file will not be accepted :(
 * Please notify a developer or make an issue if you would like to contribute to translating PenguinMod.
 *
 * If you are a developer, you can re-index the translations folder with:
 * \`npm run indexl10n\`
 *
 * Please notify a developer or make an issue if you would like to contribute to translating PenguinMod.
 */
`;

fs.writeFileSync(outputLanguagesPath, outputDatabaseText, "utf8");
console.log("wrote", outputLanguagesPath);
fs.writeFileSync(outputLanguageInfoPath, outputInfoText, "utf8");
console.log("wrote", outputLanguageInfoPath);
fs.writeFileSync(outputLanguageTypesPath, outputTypesText, "utf8");
console.log("wrote", outputLanguageTypesPath);