/**!
 * @fileoverview This file is automatically generated based off of PenguinMod's Translations Google Sheet.
 * Please notify a developer or make an issue if you would like to contribute to translating PenguinMod.
 * 
 * Do not edit this file manually. Pull requests and modifications to this file will not be accepted :(
 * Please notify a developer or make an issue if you would like to contribute to translating PenguinMod.
 * 
 * If you are a developer, you can re-index the translations folder with:
 * `npm run indexl10n`
 *
 * Please notify a developer or make an issue if you would like to contribute to translating PenguinMod.
 */
/**
 * A large table of language info.
 */
const languageInfo = {};
/**
 * The mappings of language code to language name.
 */
languageInfo.languageName = {
"ar": "العربية",
"bleh": "Bleh",
"braille": "⠑⠝⠛⠇⠊⠎⠓",
"cs": "Čeština",
"da": "Dansk",
"de": "Deutsch",
"en-but-again": "English (but again)",
"en-flipped": "ɥsıʃƃuƎ",
"en-reversed": "hsilgnE",
"en-scream": "ENGLISH!!!",
"en": "English",
"es-419": "Español (Latinoamericano)",
"es": "Español (España)",
"fa": "فارسی",
"fr-ca": "Français (Canada)",
"fr": "Français",
"he": "עברית",
"hr": "Hrvatski",
"id": "Bahasa Indonesia",
"it": "Italiano",
"ja": "日本語",
"nl": "Nederlands",
"no": "Norsk",
"pl": "Polski",
"pt-br": "Português (Brasil)",
"really-big": "REAlly big random stuff",
"ro": "Română",
"ru": "Русский",
"sk": "Slovenčina",
"sv": "Svenska",
"test": "lang.name",
"tr": "Türkçe",
"uk": "Українська",
"vi": "Tiếng Việt",
};
/**
 * The list of language codes that are marked as joke languages.
 * This is specified in `scripts/programatic-langs.js` even for non-automatically-generated languages.
 */
languageInfo.languageJokeList = ["test","en-but-again","en-scream","en-reversed","en-flipped","bleh","braille","really-big"];
/**
 * The list of language codes that are marked as Right-To-Left languages.
 * This is specified in `scripts/translation-index.js`
 */
languageInfo.languageRtlList = ["he","fa","ar","en-reversed","en-flipped"];
/**
 * Mapping of language codes that do not have translations, but map to similar languages that are.
 * This is specified in `scripts/translation-index.js`
 */
languageInfo.languageAlternative = {"nn":"no","nb":"no","es-es":"es","pt":"pt-br","fr-fr":"fr","nl-nl":"nl","ar-sa":"ar"};
/**
 * Maps whether or not a language code is a joke language.
 */
languageInfo.languageJoke = {
"ar": false,
"bleh": true,
"braille": true,
"cs": false,
"da": false,
"de": false,
"en-but-again": true,
"en-flipped": true,
"en-reversed": true,
"en-scream": true,
"en": false,
"es-419": false,
"es": false,
"fa": false,
"fr-ca": false,
"fr": false,
"he": false,
"hr": false,
"id": false,
"it": false,
"ja": false,
"nl": false,
"no": false,
"pl": false,
"pt-br": false,
"really-big": true,
"ro": false,
"ru": false,
"sk": false,
"sv": false,
"test": true,
"tr": false,
"uk": false,
"vi": false,
};
/**
 * Maps whether or not a language code is a Right-To-Left language.
 */
languageInfo.languageRtl = {
"ar": true,
"bleh": false,
"braille": false,
"cs": false,
"da": false,
"de": false,
"en-but-again": false,
"en-flipped": true,
"en-reversed": true,
"en-scream": false,
"en": false,
"es-419": false,
"es": false,
"fa": true,
"fr-ca": false,
"fr": false,
"he": true,
"hr": false,
"id": false,
"it": false,
"ja": false,
"nl": false,
"no": false,
"pl": false,
"pt-br": false,
"really-big": false,
"ro": false,
"ru": false,
"sk": false,
"sv": false,
"test": false,
"tr": false,
"uk": false,
"vi": false,
};
/**
 * The order that languages should be listed in alphabetically (A-Z).
 */
languageInfo.languageOrder = [
"braille",
"id",
"bleh",
"cs",
"da",
"de",
"en",
"en-but-again",
"en-scream",
"es",
"es-419",
"fr",
"fr-ca",
"hr",
"en-reversed",
"it",
"test",
"nl",
"no",
"pl",
"pt-br",
"really-big",
"ro",
"sk",
"sv",
"vi",
"tr",
"en-flipped",
"ru",
"uk",
"he",
"ar",
"fa",
"ja",
];
/**
 * Maps the percentage (0-1) that a language has been translated.
 */
languageInfo.finishedPercentage = {
"ar": 1,
"bleh": 1,
"braille": 1,
"cs": 0.806910569105691,
"da": 0.9806910569105691,
"de": 0.3089430894308943,
"en-but-again": 1,
"en-flipped": 1,
"en-reversed": 1,
"en-scream": 1,
"en": 1,
"es-419": 0.9949186991869918,
"es": 0.9939024390243902,
"fa": 0.8485772357723578,
"fr-ca": 0.27540650406504064,
"fr": 0.4268292682926829,
"he": 0.5457317073170732,
"hr": 0.3434959349593496,
"id": 0.1290650406504065,
"it": 0.3516260162601626,
"ja": 1,
"nl": 0.948170731707317,
"no": 0.43902439024390244,
"pl": 0.2306910569105691,
"pt-br": 0.967479674796748,
"really-big": 1,
"ro": 0.35060975609756095,
"ru": 0.9969512195121951,
"sk": 0.24491869918699186,
"sv": 0.25,
"test": 1,
"tr": 0.9949186991869918,
"uk": 0.36890243902439024,
"vi": 0.8302845528455285,
};
export default languageInfo;

/**!
 * @fileoverview This file is automatically generated based off of PenguinMod's Translations Google Sheet.
 * Please notify a developer or make an issue if you would like to contribute to translating PenguinMod.
 * 
 * Do not edit this file manually. Pull requests and modifications to this file will not be accepted :(
 * Please notify a developer or make an issue if you would like to contribute to translating PenguinMod.
 * 
 * If you are a developer, you can re-index the translations folder with:
 * `npm run indexl10n`
 *
 * Please notify a developer or make an issue if you would like to contribute to translating PenguinMod.
 */

